import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "th" | "en";

export const translations = {
  th: {
    // Sidebar
    sidebar_customer_menu: "เมนูสำหรับลูกค้า",
    sidebar_admin_menu: "จัดการระบบ (Admin)",
    sidebar_storefront: "หน้าร้านค้า",
    sidebar_cart: "ตะกร้าสินค้า",
    sidebar_orders: "ประวัติสั่งซื้อ",
    sidebar_management: "จัดการระบบ",
    sidebar_shop_settings: "ตั้งค่าร้านค้า",
    sidebar_line_setup: "ตั้งค่าระบบ LINE API",
    sidebar_login: "เข้าสู่ระบบ",
    sidebar_profile: "บัญชีผู้ใช้ (Profile)",
    sidebar_logout: "ออกจากระบบ",
    sidebar_simulation: "สถานะระบบจำลอง",
    sidebar_connected_line: "เชื่อมต่อกับ LINE OA",

    // App Header & Global
    header_recommend: "💡 แนะนำ: เข้าสู่ระบบ เพื่อรับบริการที่สมบูรณ์แบบ",
    header_storefront: "🛒 หน้าร้านพรีเมียม (Storefront)",
    header_cart: "🛍️ ตะกร้าสินค้าและการชำระเงิน (Cart)",
    header_orders: "📋 ประวัติคำสั่งซื้อส่วนตัว (Orders)",
    header_admin: "👑 ระบบจัดการผู้ดูแลร้าน (Management)",
    header_settings: "⚙️ ตั้งค่าระบบร้านค้า (Shop Settings)",
    header_line: "⚙️ ตั้งค่าคีย์ LINE API (Settings)",
    header_auth: "🔑 บัญชีระบบสมาชิก S Shop",
    header_profile: "👤 บัญชีผู้ใช้ของฉัน (My Profile)",
    btn_show_line: "ดูจำลอง LINE",
    btn_hide_line: "ซ่อนจำลอง LINE",
    loading_data: "กำลังประสานฐานข้อมูลหลังบ้านร้านค้า...",

    // ShopView
    shop_subtitle: "S Shop Online x LINE Integration",
    shop_title: "ช้อปสินค้าพรีเมียมง่ายๆ ผ่าน LINE และแจ้งเตือนออเดอร์ทันที",
    shop_desc: "เลือกช้อปสินค้าดีไซน์มินิมอล พร้อมระบบแจ้งเตือนออเดอร์เข้าสู่อุปกรณ์ LINE ของร้านค้าโดยตรงเมื่อคุณสั่งซื้อ!",
    shop_all_products: "สินค้าทั้งหมด",
    shop_promotions: "โปรโมชั่นพิเศษ",
    shop_bestsellers: "สินค้าขายดี",
    shop_search_placeholder: "ค้นหาชื่อสินค้า...",
    shop_no_products: "ไม่พบสินค้าที่ค้นหา",
    shop_add_to_cart: "เพิ่มลงตะกร้า",
    shop_adding: "กำลังเพิ่ม...",
    shop_added: "เพิ่มแล้ว! ✓",
    shop_bath: "บาท",
    shop_stock: "คงเหลือ",
    shop_out_of_stock: "สินค้าหมด",

    // CartView
    cart_title: "รายการสินค้าในตะกร้า",
    cart_empty: "ตะกร้าสินค้าของคุณว่างเปล่า",
    cart_empty_title: "ตะกร้าสินค้าว่างเปล่า",
    cart_empty_desc: "ท่านยังไม่ได้เลือกสินค้าเข้าสู่ตะกร้า ไปที่หน้าร้านค้าเพื่อเพิ่มสินค้าอัจฉริยะลงในตะกร้าได้เลย!",
    cart_clear: "ล้างตะกร้าสินค้า",
    cart_go_shopping: "ไปเลือกซื้อสินค้า",
    cart_summary: "สรุปรายการสั่งซื้อ",
    cart_subtotal: "ราคาสินค้ารวม",
    cart_shipping: "ค่าจัดส่ง",
    cart_discount: "ส่วนลด",
    cart_total: "ยอดชำระทั้งหมด",
    cart_coupon_placeholder: "กรอกโค้ดส่วนลด (เช่น SPECIAL10)",
    cart_apply_coupon: "ใช้โค้ด",
    cart_checkout_title: "ข้อมูลจัดส่งสินค้า (LINE Address)",
    cart_fullname: "ชื่อ-นามสกุล ผู้รับ *",
    cart_phone: "เบอร์โทรศัพท์ติดต่อ *",
    cart_address: "ที่อยู่จัดส่งสินค้าโดยละเอียด *",
    cart_payment_title: "ช่องทางการชำระเงิน (สแกน QR Code)",
    cart_payment_desc: "สแกน QR Code ด้านล่างเพื่อโอนเงินผ่าน PromptPay และแนบหลักฐานการโอนเงิน (สลิป)",
    cart_bank_details: "บัญชีธนาคารสำหรับโอนเงิน",
    cart_upload_slip: "อัปโหลดสลิปการโอนเงินเพื่อยืนยันออเดอร์",
    cart_choose_file: "เลือกไฟล์ภาพสลิป",
    cart_drag_drop: "หรือลากและวางไฟล์ภาพที่นี่",
    cart_order_btn: "ยืนยันคำสั่งซื้อและสรุปเข้า LINE",
    cart_ordering: "กำลังบันทึกและส่งเข้า LINE...",
    cart_req_fullname: "กรุณากรอกชื่อผู้รับ",
    cart_req_phone: "กรุณากรอกเบอร์โทรศัพท์",
    cart_req_address: "กรุณากรอกที่อยู่จัดส่ง",
    cart_req_slip: "กรุณาแนบภาพหลักฐานสลิปโอนเงิน",
    cart_coupon_invalid: "รหัสคูปองไม่ถูกต้องหรือไม่ผ่านเงื่อนไขขั้นต่ำ",
    cart_coupon_success: "ใช้โค้ดส่วนลดสำเร็จ!",
    cart_shipping_title: "ข้อมูลจัดส่งสินค้า (LINE Address)",
    cart_use_previous: "ใช้ที่อยู่เดิมจากการสั่งซื้อครั้งก่อน",
    cart_recipient_name: "ชื่อ-นามสกุลผู้รับ",
    cart_recipient_phone: "เบอร์โทรศัพท์ติดต่อ",
    cart_shipping_details: "ที่อยู่สำหรับจัดส่ง (Shipping Address)",
    cart_address_house: "บ้านเลขที่, อาคาร, ซอย, ถนน *",
    cart_zipcode: "รหัสไปรษณีย์ *",
    cart_province: "จังหวัด *",
    cart_district: "เขตหรืออำเภอ *",
    cart_subdistrict: "ตำบลหรือแขวง *",
    cart_submit_note: "เมื่อกด \"ยืนยันคำสั่งซื้อ\" ระบบจะทำการส่งข้อความสรุปพร้อมรูปภาพสลิปเข้าไปจำลองแชท LINE OA/Notify ทันที!",
    cart_cost_summary: "ยอดเงินที่ต้องชำระ",
    cart_coupon_discount: "ส่วนลดคูปอง",
    cart_coupon_title: "คูปองส่วนลด (Coupon Code)",
    cart_bank_payment: "ชำระเงินผ่านบัญชีธนาคาร (BANK TRANSFER)",
    cart_bank_info: "ข้อมูลบัญชีรับโอนเงิน",
    cart_bank_name: "ธนาคาร",
    cart_bank_no: "เลขที่บัญชี",
    cart_bank_account: "ชื่อบัญชี",
    cart_attach_slip: "แนบหลักฐานการโอนเงิน (สลิปโอนเงิน)",
    cart_submit: "ยืนยันคำสั่งซื้อและสรุปเข้า LINE",

    // OrdersHistoryView
    orders_title: "ประวัติการสั่งซื้อของคุณ",
    orders_empty: "คุณยังไม่มีประวัติการสั่งซื้อ",
    orders_id: "เลขออเดอร์",
    orders_date: "วันที่สั่งซื้อ",
    orders_status: "สถานะการชำระเงิน",
    orders_shipping: "สถานะการจัดส่ง",
    orders_items: "รายการสินค้า",
    orders_total: "ยอดชำระเงิน",
    orders_slip_preview: "หลักฐานการโอนเงิน",
    orders_tracking: "เลขพัสดุจัดส่ง",
    orders_track_btn: "ติดตามพัสดุ",
    orders_cancel_btn: "ยกเลิกออเดอร์",
    orders_cancelled: "ยกเลิกแล้ว",
    orders_refund_desc: "ระบบจะแจ้งเตือนยกเลิกไปยังร้านค้าทาง LINE",

    // AuthView
    auth_title: "เข้าสู่ระบบสมาชิก S Shop",
    auth_desc: "สร้างบัญชีลูกค้า หรือใช้ระบบล็อกอินจำลองผ่านระบบ LINE ได้ทันที!",
    auth_email: "อีเมลของคุณ",
    auth_password: "รหัสผ่าน",
    auth_login_btn: "เข้าสู่ระบบทั่วไป",
    auth_line_btn: "เข้าสู่ระบบผ่านแอป LINE (Simulated)",
    auth_no_account: "ยังไม่มีบัญชีใช่ไหม? สมัครสมาชิก",
    auth_have_account: "มีบัญชีแล้วใช่ไหม? เข้าสู่ระบบ",
    auth_register_btn: "สมัครสมาชิกใหม่",
    auth_sim_modal_title: "LINE Login SSO Gateway",
    auth_sim_modal_desc: "จำลองหน้าต่างขอสิทธิ์การยินยอมเชื่อมต่อกับระบบ LINE OA",
    auth_sim_select_profile: "กรุณาเลือกโปรไฟล์ LINE ที่ต้องการใช้ล็อกอิน:",

    // LineSimulator
    sim_title: "จำลองแอป LINE / Notify",
    sim_tab_chat: "แชท LINE",
    sim_tab_tech: "Technical Logs",
    sim_send_test: "พิมพ์ข้อความทดสอบ LINE...",
    sim_send_btn: "ส่งทดสอบ",
    sim_clear_logs: "ล้างประวัติจำลอง",

    // AdminView
    admin_dashboard_title: "ระบบจัดการผู้ดูแลร้าน",
    admin_all_orders: "รายการคำสั่งซื้อทั้งหมด",
    admin_buyer_line: "โปรไฟล์ LINE ผู้ซื้อ",
    admin_action: "ดำเนินการ",
    admin_update_status: "อัปเดตสถานะออเดอร์",
    admin_approve_payment: "อนุมัติการชำระเงิน (Paid)",
    admin_reject_payment: "ปฏิเสธการชำระเงิน (Failed)",
    admin_ship_order: "ส่งสินค้าและระบุเลขพัสดุ",
    admin_cancel_order: "ยกเลิกออเดอร์นี้",

    // ShopSettingsView
    settings_title: "ตั้งค่าข้อมูลร้านค้าและการชำระเงิน",
    settings_store_name: "ชื่อร้านค้าหลัก *",
    settings_promptpay_id: "หมายเลข PromptPay ID *",
    settings_promptpay_name: "ชื่อบัญชีพร้อมเพย์ *",
    settings_shipping_fee: "ค่าจัดส่งคงที่ (บาท) *",
    settings_free_shipping: "จัดส่งฟรีเมื่อยอดซื้อขั้นต่ำ (บาท)",
    settings_save: "บันทึกการตั้งค่า",

    // LineSetupView
    line_setup_title: "ตั้งค่า LINE Notifications Integration",
    line_setup_desc: "เชื่อมต่อระบบร้านค้าเข้ากับระบบแจ้งเตือน LINE เพื่อรับออเดอร์และแจ้งส่งเลขพัสดุของลูกค้าเข้า LINE อัตโนมัติ",
    line_method: "วิธีการแจ้งเตือน",
    line_notify_token: "LINE Notify Token สำหรับร้านค้า (กลุ่มร้านค้า) *",
    line_oa_token: "LINE OA Channel Access Token *",
    line_oa_admin_id: "Admin LINE User ID (สำหรับรับแจ้งเตือนร้าน) *",
    line_save: "บันทึกการเชื่อมต่อ LINE",

    // Order Success Modal
    success_order_title: "สั่งซื้อสินค้าเสร็จสิ้น!",
    success_order_desc: "ออเดอร์ได้รับการบันทึกในฐานข้อมูลเรียบร้อยแล้ว รายละเอียดรายการสินค้า ยอดชำระ และข้อมูลผู้จัดส่งถูกส่งตรงไปยัง LINE Official (จำลองแชทฝั่งขวา) แล้ว!",
    success_order_summary: "สรุปแจ้งเตือนที่จะปรากฏบน LINE:",
    success_view_history: "ดูประวัติการสั่งซื้อ",
    success_continue: "เลือกซื้อสินค้าต่อ",
  },
  en: {
    // Sidebar
    sidebar_customer_menu: "Customer Menu",
    sidebar_admin_menu: "Management (Admin)",
    sidebar_storefront: "Storefront",
    sidebar_cart: "Cart",
    sidebar_orders: "My Orders",
    sidebar_management: "Management",
    sidebar_shop_settings: "Shop Settings",
    sidebar_line_setup: "LINE API Settings",
    sidebar_login: "Login / Register",
    sidebar_profile: "My Profile",
    sidebar_logout: "Logout",
    sidebar_simulation: "Simulator Status",
    sidebar_connected_line: "CONNECTED TO LINE OA",

    // App Header & Global
    header_recommend: "💡 Recommendation: Login to unlock the full premium experience",
    header_storefront: "🛒 Storefront",
    header_cart: "🛍️ Cart & Checkout",
    header_orders: "📋 Order History",
    header_admin: "👑 Admin Management Panel",
    header_settings: "⚙️ Shop Configuration Settings",
    header_line: "⚙️ LINE API Settings",
    header_auth: "🔑 S Shop Membership Account",
    header_profile: "👤 My Profile & Settings",
    btn_show_line: "Show LINE Simulator",
    btn_hide_line: "Hide LINE Simulator",
    loading_data: "Synchronizing with storefront databases...",

    // ShopView
    shop_subtitle: "S Shop Online x LINE Integration",
    shop_title: "Shop Premium Goods & Get Instant LINE Notifications",
    shop_desc: "Discover our curated list of minimalist products, and enjoy direct LINE notification alerts sent straight to the merchant's device!",
    shop_all_products: "All Products",
    shop_promotions: "Special Offers",
    shop_bestsellers: "Bestsellers",
    shop_search_placeholder: "Search products...",
    shop_no_products: "No products found matching your search",
    shop_add_to_cart: "Add to Cart",
    shop_adding: "Adding...",
    shop_added: "Added! ✓",
    shop_bath: "THB",
    shop_stock: "In stock",
    shop_out_of_stock: "Out of Stock",

    // CartView
    cart_title: "Items in your cart",
    cart_empty: "Your cart is currently empty",
    cart_empty_title: "Your shopping cart is empty",
    cart_empty_desc: "You haven't selected any items yet. Visit our shop view to add premium products to your cart!",
    cart_clear: "Clear All Cart",
    cart_go_shopping: "Continue Shopping",
    cart_summary: "Order Summary",
    cart_subtotal: "Subtotal Amount",
    cart_shipping: "Shipping Cost",
    cart_discount: "Discount",
    cart_total: "Grand Total",
    cart_coupon_placeholder: "Promo Code (e.g. SPECIAL10)",
    cart_apply_coupon: "Apply",
    cart_checkout_title: "Shipping Address (LINE Address)",
    cart_fullname: "Recipient's Name *",
    cart_phone: "Contact Number *",
    cart_address: "Full Delivery Address *",
    cart_payment_title: "Payment Method (Scan QR Code)",
    cart_payment_desc: "Scan the QR code below to transfer via PromptPay, and attach your transfer slip (receipt) as proof.",
    cart_bank_details: "Bank Transfer Account Info",
    cart_upload_slip: "Upload Transfer Slip to Confirm Order",
    cart_choose_file: "Choose Slip image",
    cart_drag_drop: "or drag and drop receipt file here",
    cart_order_btn: "Confirm Order & Notify LINE",
    cart_ordering: "Saving & dispatching to LINE...",
    cart_req_fullname: "Please specify recipient's name",
    cart_req_phone: "Please specify phone number",
    cart_req_address: "Please specify delivery address",
    cart_req_slip: "Please attach a payment receipt/slip image",
    cart_coupon_invalid: "Invalid coupon or minimum spend condition not met",
    cart_coupon_success: "Discount applied successfully!",
    cart_shipping_title: "Delivery Details (LINE Address)",
    cart_use_previous: "Use previous delivery address",
    cart_recipient_name: "Recipient's Full Name",
    cart_recipient_phone: "Contact Phone Number",
    cart_shipping_details: "Delivery Address Details",
    cart_address_house: "House No., Street, Building, Village *",
    cart_zipcode: "Postal/Zip Code *",
    cart_province: "Province *",
    cart_district: "District *",
    cart_subdistrict: "Subdistrict *",
    cart_submit_note: "By confirming your order, a simulated summary text with transfer slip will be sent immediately to the LINE client simulator (right side panel)!",
    cart_cost_summary: "Total Amount to Pay",
    cart_coupon_discount: "Coupon Discount",
    cart_coupon_title: "Coupon Discount Code",
    cart_bank_payment: "Pay via Bank Transfer",
    cart_bank_info: "Beneficiary Bank Account Info",
    cart_bank_name: "Bank Name",
    cart_bank_no: "Account Number",
    cart_bank_account: "Account Name",
    cart_attach_slip: "Attach Payment Slip / Proof of Transfer",
    cart_submit: "Confirm Order & Summary to LINE",

    // OrdersHistoryView
    orders_title: "Your Order History",
    orders_empty: "You have not placed any orders yet",
    orders_id: "Order ID",
    orders_date: "Order Date",
    orders_status: "Payment Status",
    orders_shipping: "Shipping Status",
    orders_items: "Items Purchased",
    orders_total: "Amount Paid",
    orders_slip_preview: "Transfer Receipt Slip",
    orders_tracking: "Tracking Number",
    orders_track_btn: "Track Package",
    orders_cancel_btn: "Cancel Order",
    orders_cancelled: "Cancelled",
    orders_refund_desc: "Merchant will be notified of the cancellation via LINE",

    // AuthView
    auth_title: "Login to S Shop Member Space",
    auth_desc: "Create an account, or log in instantly using the simulated LINE SSO provider!",
    auth_email: "Email Address",
    auth_password: "Password",
    auth_login_btn: "Standard Login",
    auth_line_btn: "Login with LINE (Simulated)",
    auth_no_account: "Don't have an account? Sign Up",
    auth_have_account: "Already have an account? Login",
    auth_register_btn: "Register Account",
    auth_sim_modal_title: "LINE Login SSO Gateway",
    auth_sim_modal_desc: "Simulated consent approval dialog with LINE Official Account Integration",
    auth_sim_select_profile: "Please select a LINE user profile to authenticate:",

    // LineSimulator
    sim_title: "LINE App Simulator",
    sim_tab_chat: "LINE Chat",
    sim_tab_tech: "Technical Logs",
    sim_send_test: "Type test message...",
    sim_send_btn: "Send",
    sim_clear_logs: "Clear Logs",

    // AdminView
    admin_dashboard_title: "Admin Management Dashboard",
    admin_all_orders: "All Merchant Orders",
    admin_buyer_line: "Buyer LINE Profile",
    admin_action: "Action",
    admin_update_status: "Update Order Status",
    admin_approve_payment: "Approve Payment (Paid)",
    admin_reject_payment: "Reject Payment (Failed)",
    admin_ship_order: "Dispatch & Provide Tracking",
    admin_cancel_order: "Cancel this Order",

    // ShopSettingsView
    settings_title: "Store & Payment Settings",
    settings_store_name: "Store Display Name *",
    settings_promptpay_id: "PromptPay ID *",
    settings_promptpay_name: "Account Name *",
    settings_shipping_fee: "Flat Rate Shipping Fee (THB) *",
    settings_free_shipping: "Free Shipping Minimum Spend (THB)",
    settings_save: "Save Configurations",

    // LineSetupView
    line_setup_title: "LINE Notifications Integration Settings",
    line_setup_desc: "Connect your web application with LINE Notify / Messaging APIs to receive real-time order alerts and push updates back to customers.",
    line_method: "Notification Delivery Method",
    line_notify_token: "Merchant LINE Notify Token (Group Notification) *",
    line_oa_token: "LINE Official Account Channel Access Token *",
    line_oa_admin_id: "Admin LINE User ID (For receiving store alerts) *",
    line_save: "Save Connection Keys",

    // Order Success Modal
    success_order_title: "Order Placed Successfully!",
    success_order_desc: "Your order has been recorded in the database. Product list, total amount, and delivery details have been pushed directly to your LINE chat simulator (on the right pane)!",
    success_order_summary: "LINE notification text summary:",
    success_view_history: "View Order History",
    success_continue: "Continue Shopping",
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof typeof translations["th"]) => string;
}

export const LanguageContext = createContext<LanguageContextType>({
  lang: "th",
  setLang: () => {},
  t: (key) => translations["th"][key] || (key as string),
});

export const useTranslation = () => useContext(LanguageContext);
